@startuml
class TranspostationSearchResponse {
}
class Transportation <<partial>> {
    + Token : string <<get>> <<set>>
    + Vendor : string <<get>> <<set>>
    + Provider : string <<get>> <<set>>
    + CompanyName : string <<get>> <<set>>
    + RouteName : string <<get>> <<set>>
    + TermsAndConditions : string <<get>> <<set>>
    + StartDate : string <<get>> <<set>>
}
class VehicleType <<partial>> {
    + VehicleTypeCode : string <<get>> <<set>>
}
class Category <<partial>> {
    + CategoryCode : string <<get>> <<set>>
    + CategoryName : string <<get>> <<set>>
    + AvailableQuantity : int <<get>> <<set>>
    + MaxPaxCapacity : int <<get>> <<set>>
}
class ItemBreakdown {
    + Date : DateTime? <<get>> <<set>>
    + ExchangeRate : decimal <<get>> <<set>>
    + LocalAmount : decimal <<get>> <<set>>
    + LocalCurrencyCode : string <<get>> <<set>>
    + Quantity : int <<get>> <<set>>
    + RoomNumber : int <<get>> <<set>>
    + SurchargeTypeId : int <<get>> <<set>>
    + TaxTypeId : int <<get>> <<set>>
    + UsdAmount : decimal <<get>> <<set>>
    + TaxProtoTypeId : int <<get>> <<set>>
}
class AdditionalService <<partial>> {
    + Code : long <<get>> <<set>>
    + Description : string <<get>> <<set>>
}
class Config {
    + Key : string <<get>> <<set>>
    + Value : string <<get>> <<set>>
}
class Policy <<partial>> {
    + Type : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + IsCurrentPolicy : bool <<get>> <<set>>
    + IsNoShow : bool <<get>> <<set>>
}
class DateCriteria {
    + StartDate : string <<get>> <<set>>
    + EndDate : string <<get>> <<set>>
}
enum BreakdownType {
    None= 0,
    RoomCharge= 1,
    Surcharge= 2,
    CancellationFee= 3,
    ExtraBed= 4,
    Discount= 5,
    BestPriceGuarantee= 6,
    StaffDiscount= 7,
    CancellationPolicy= 8,
    Other= 9,
    NoshowFee= 10,
    TravelVisa= 11,
    GroundTransportation= 12,
}
enum BreakdownItemId {
    None= 0,
    NetExclusive= 1,
    Tax= 2,
    Margin= 3,
    Commission= 4,
    ProcessingFee= 5,
    DiscountPromotion= 6,
    Uplift= 7,
    AffiliateCommission= 8,
    Downlift= 9,
    NetInclusive= 10,
    SalesExclusive= 11,
    SalesInclusive= 12,
    Payment= 13,
    AccruedRewardPoints= 14,
    YcsPromotion= 15,
    Fee= 16,
    PartnerDiscount= 17,
    PartnerDiscountToBePaid= 18,
    ExchangeRateDifference= 19,
    BankCharges= 20,
    ConcurExpense= 21,
    ConcurTax= 22,
    ConcurAdvance= 23,
    UpcPayment= 24,
    UpcAdjustment= 25,
    StaffDiscount= 26,
    BestPrice= 27,
    OtherAdjustment= 28,
    Ebe= 29,
    UpcOvercharge= 30,
    APClearing= 31,
    InputGst= 32,
    FxGainAndLoss= 33,
    WexUplift= 34,
    TransactionCost= 35,
    CashInTransit= 36,
    UpcCostAdjustment= 37,
    B2BCommission= 38,
    LoyaltyDiscount= 39,
    AccRateDifference= 40,
    ReferenceSalesInclusive= 41,
    AgodaAgencyCommission= 42,
    TotMarginTaxCollected= 43,
    TotMarginFeeCollected= 44,
}
class Model <<partial>> {
    + From : long <<get>> <<set>>
    + To : long <<get>> <<set>>
}
class "List`1"<T> {
}
TranspostationSearchResponse --> "Transportations<Transportation>" "List`1"
Transportation --> "VehicleTypes<VehicleType>" "List`1"
Transportation --> "Policies<Policy>" "List`1"
VehicleType --> "Categories<Category>" "List`1"
Category --> "Model" Model
Category --> "DisplayRateInfo<ItemBreakdown>" "List`1"
Category --> "AdditionalServices<AdditionalService>" "List`1"
ItemBreakdown --> "ItemId" BreakdownItemId
ItemBreakdown --> "Type" BreakdownType
AdditionalService --> "DisplayRateInfo<ItemBreakdown>" "List`1"
Policy --> "DateCriteria" DateCriteria
Policy --> "Criteria<Config>" "List`1"
@enduml
